### ISSUE TITLE
异常

### ISSUE THREAD

**Issue by zj-captain** [liujingxing/RxHttp#22]
正在请求的时候，点击返回退出界面的时候会报这个错： io.reactivex.exceptions.UndeliverableException:The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with.
请问怎么解决？

**Comment by liujingxing** [comment]
这个不是RxHttp的问题，这是RxJava的设计原则(不吃掉任何一个异常)。当页面销毁时，RxJava 管道会断开并中断请求，此时上游出现异常，下游无人处理，就崩溃了。解决办法是，在Application中注册一个RxJava的全局异常处理。可以参考Demo里的AppHolder类中的37行https://github.com/liujingxing/RxHttp/blob/master/app/src/main/java/com/example/httpsender/AppHolder.java

**Comment by HancockY** [comment]
我也是类似这个问题:
android版本: 4.3, api18.
加了RxJavaPlugins.setErrorHandler(e -> { });之后不崩溃了, 但是还是报错不能获取到结果.
但是在android 8.1 api 27 的手机上就没问题....
在4.3上的报错是:Caused by: java.lang.NoClassDefFoundError: java.util.Objects
请教一下有解决的办法么


AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
    io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.NoClassDefFoundError: java.util.Objects
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:234)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.NoClassDefFoundError: java.util.Objects
        at okhttp3.CertificatePinner.withCertificateChainCleaner(CertificatePinner.java:231)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:238)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
        at rxhttp.HttpSender.getDefaultOkHttpClient(HttpSender.java:186)
        at rxhttp.HttpSender.getOkHttpClient(HttpSender.java:50)
        at rxhttp.HttpSender.newCall(HttpSender.java:144)
        at rxhttp.ObservableHttp.execute(ObservableHttp.java:80)
        at rxhttp.ObservableHttp.subscribeActual(ObservableHttp.java:58)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:234) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
        at java.lang.Thread.run(Thread.java:841)
