### ISSUE TITLE
上传大文件时

### ISSUE THREAD

**Issue by ming123aaa** [liujingxing/rxhttp#250]
代码:
```kotlin
GlobalScope.launch {
RxHttp.postForm(Http.Main.FileUpload())
                .addPart(this@MainActivity, "fileName", fileUri)
                .upload(this) {
//....
                }
                .awaitString()
}
```

报错:
```
java.lang.IllegalArgumentException: The contentLength cannot be greater than 2147483647 bytes, the current contentLength is 3754628053 bytes
	at rxhttp.wrapper.param.AbstractBodyParam.buildRequestBody(AbstractBodyParam.java:36)
	at rxhttp.wrapper.utils.BuildUtil.buildRequest(BuildUtil.java:28)
	at rxhttp.wrapper.param.AbstractParam.buildRequest(AbstractParam.java:220)
	at rxhttp.wrapper.param.RxHttp.buildRequest(RxHttp.java:456)
	at rxhttp.wrapper.param.RxHttp.newCall(RxHttp.java:447)
	at rxhttp.wrapper.await.AwaitImpl.await(AwaitImpl.kt:23)
	at rxhttp.IRxHttpKt.await(IRxHttp.kt:67)
	at rxhttp.IRxHttpKt.awaitString(IRxHttp.kt:268)
	at com.example.filemanager.MainActivity$rxhttpUpload$1.invokeSuspend(MainActivity.kt:152)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

有什么解决办法吗

**Comment by liujingxing** [comment]
文件长度超过int最大值了

**Comment by liujingxing** [comment]
@ming123aaa RxHttp版本已更新至2.6.1，详细查看[更新日志](https://github.com/liujingxing/rxhttp/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)
