### ISSUE TITLE
 Request end Log printing failed     java.io.EOFException

### ISSUE THREAD

**Issue by ppg408331701** [liujingxing/rxhttp#285]
```
java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
        at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.kt:381)
        at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.kt:429)
        at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:408)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
        at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
        at rxhttp.wrapper.utils.LogUtil.response2Str(LogUtil.java:287)
        at rxhttp.wrapper.utils.LogUtil.log(LogUtil.java:165)
        at rxhttp.wrapper.utils.Converter.convert(Converter.kt:43)
        at com.gxrcw.lib_common.http.ResponseParser.onParse(ResponseParser.kt:47)
        at rxhttp.wrapper.utils.CallKt$await$4$2.onResponse(Call.kt:44)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
```

有几个接口轮流出现这个报错，不固定，有点摸不着头脑

**Comment by ppg408331701** [comment]
版本。okhttp 4.9.1
rxhttp  2.6.5

**Comment by ppg408331701** [comment]
晚上说有可能是服务器提前关闭了连接导致的。我之后和后台研究一下，如果有问题在重写打开

**Comment by ppg408331701** [comment]
参考，这个，可能是这个的原因
https://www.pianshen.com/article/5300797751/
