### ISSUE TITLE
解析数据报错，ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by chenyinchao** [liujingxing/rxhttp#289]
当在Android5.1.1版本使用报错如下，而在Android7.1.1，9.0版本都没报错，这个怎么解决 啊？

args[0] = throwable name: java.lang.ArrayIndexOutOfBoundsException
args[1] = java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at com.google.gson.internal.$Gson$Types.getGenericSupertype($Gson$Types.java:248)
	at com.google.gson.internal.$Gson$Types.getSupertype($Gson$Types.java:284)
	at com.google.gson.internal.$Gson$Types.getCollectionElementType($Gson$Types.java:302)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.fromJson(Gson.java:931)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at rxhttp.wrapper.converter.GsonConverter.convert(GsonConverter.java:59)
	at rxhttp.wrapper.utils.Converter.convert(Converter.kt:45)
	at rxhttp.wrapper.parse.AbstractParser.convert(AbstractParser.kt:33)
	at com.galaxis.paser.ResultListPaser.onParse(ResultListPaser.java:40)
	at com.galaxis.paser.ResultListPaser.onParse(ResultListPaser.java:21)
	at rxhttp.wrapper.param.ObservableParser$SyncParserObserver.onNext(ObservableParser.java:103)
	at rxhttp.wrapper.param.ObservableParser$SyncParserObserver.onNext(ObservableParser.java:54)
	at rxhttp.wrapper.param.ObservableCallEnqueue$HttpDisposable.onResponse(ObservableCallEnqueue.java:79)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Thread

环境是：
rxhttp                       : "2.6.5",
rxlife                       : "2.1.0",
okhttp                       : "3.12.6",
rxandroid                    : "2.1.1",
rxjava                       : "2.2.8",

Android Studio Arctic Fox | 2020.3.1

compileSdkVersion: 28,
buildToolsVersion: "28.0.3",
minSdkVersion    : 19,
targetSdkVersion : 28,
versionCode      : 1,
versionName      : "1.0.0"

classpath 'com.android.tools.build:gradle:4.0.1'
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip

**Comment by liujingxing** [comment]
`ResultListPaser `代码贴出来看看

**Comment by chenyinchao** [comment]
> `ResultListPaser `代码贴出来看看

@Parser(name = "ResultListPaser")
public class ResultListPaser<T> extends AbstractParser<ResultArrayList<T>> {

    public ResultListPaser() {
        super();
    }

    public ResultListPaser(Type type) {
        super(type);
    }

    public static <T> ResultListPaser<T> get(Class<T> type) {
        return new ResultListPaser<>(type);
    }

    @Override
    public ResultArrayList<T> onParse(Response response) throws IOException {
        final Type type = ParameterizedTypeImpl.get(Result.class, ResultArrayList.class, mType);
        Result<ResultArrayList<T>> result = convert(response, type);
        if (result == null) {
            throw new ParseException("data parse fail", response, "0");
        }
        if (!result.isSuccess()) {
            throw new ParseException(result.getMsg(), response, "1");
        }

        ResultArrayList<T> t = result.getData();
        if (t == null) {
            throw new ParseException(result.getMsg() + "：后端返回data为null", response, "2");
        }

        Pagination page = result.getPagination();
        if (page != null) {
            t.setCount(page.getCount());
            t.setFirst(page.getFirst());
            t.setLast(page.getLast());
            t.setNext(page.getNext());
            t.setPageNo(page.getPageNo());
            t.setPageSize(page.getPageSize());
            t.setPrev(page.getPrev());
        }
        return t;
    }
}

**Comment by liujingxing** [comment]
请求代码也看看，另外`final Type type = ParameterizedTypeImpl.get(Result.class, ResultArrayList.class, mType)`调试下这行代码，看看`mType`字段的值

**Comment by chenyinchao** [comment]
> 请求代码也看看，另外 `final Type type = ParameterizedTypeImpl.get(Result.class, ResultArrayList.class, mType)` 调试下这行代码，看看 `mType` 字段的值

在 Android5.1.1 版本使用报这个错，在 Android7.1.1，9.0 版本都没报错

  RxHttp.postForm(Url.Api.LoginApi.query).setDomainToWarehouseIfAbsent().setAssemblyEnabled(false)
            .asResultListPaser(Info.class)
            .as(RxLife.asOnMain(context)).subscribe(infos -> {
                getView().handleQuery(infos );
            }, (OnError)throwable -> {
                getView().handleQueryError();
            });

**Comment by liujingxing** [comment]
你的`rxhttp-compiler`版本多少？看你解析器无参构造方法没有声明为`protected`应该编译不通过的。

**Comment by chenyinchao** [comment]
我最近为了兼容minSdkVersion 19，同时用上java8 stream流，修改以下代码导致问题出现：
1、把minSdkVersion : 24,     改成 minSdkVersion : 19
2、把 classpath 'com.android.tools.build:gradle:3.5.3' 改成 classpath 'com.android.tools.build:gradle:4.0.1'

rxhttp-compiler 版本是2.6.5

// 是protected，刚才粘错了
protected ResultListPaser() {
        super();
    }

**Comment by liujingxing** [comment]
我这找不到Android 5.1.1设备，用android 11的设备试了下，是不会走`com.google.gson.internal.$Gson$Types.getGenericSupertype($Gson$Types.java:248)`的。

对了，gson版本是2.8.7吧？

**Comment by liujingxing** [comment]
简单看了下源码，跟Android 版本应该是没关系的，你确定只有Android 5.1.1的设备才有问题吗？

**Comment by chenyinchao** [comment]
> 简单看了下源码，跟 Android 版本应该是没关系的，你确定只有 Android 5.1.1 的设备才有问题吗？

是的，我手上有5.1.1真机版本，就这个版本报错，模拟器用7.1.1没报错，真机9.0也没报错

**Comment by chenyinchao** [comment]
> 我这找不到 Android 5.1.1 设备，用 android 11 的设备试了下，是不会走 `com.google.gson.internal.$Gson$Types.getGenericSupertype($Gson$Types.java:248)` 的。
> 
> 对了，gson 版本是 2.8.7 吧？

  gson  是 : "2.8.2",

**Comment by liujingxing** [comment]
先升级版本试试吧

**Comment by chenyinchao** [comment]
> 先升级版本试试吧

gson 升级成2.8.7 还是不行，一样的报错

**Comment by chenyinchao** [comment]
> 先升级版本试试吧

我把Converter换成 implementation 'com.github.liujingxing.rxhttp:converter-fastjson:2.6.5' 就好了
