### ISSUE TITLE
rxhttp.wrapper.exception.HttpStatusCodeException

### ISSUE THREAD

**Issue by chenyinchao** [liujingxing/rxhttp#295]
接着上一个请求（正常的），过2分钟后请求这个接口，报403。发现没有header了，不知为什么

<------ rxhttp/2.6.5 okhttp/4.7.2 request end ------>
rxhttp.wrapper.exception.HttpStatusCodeException:
GET http://...

http/1.1 403 
X-Application-Context: jl:project:8686
Content-Type: application/json;charset=utf-8
Transfer-Encoding: chunked
Date: Thu, 19 Aug 2021 02:13:13 GMT

{
"success": false,
"message": "用户认证不通过，Token无效。"
}
	at rxhttp.wrapper.exception.ExceptionHelper.throwIfFatal(ExceptionHelper.java:33)
	at rxhttp.wrapper.utils.Converter.convert(Converter.kt:41)
	at rxhttp.wrapper.parse.AbstractParser.convert(AbstractParser.kt:33)
	at com.galaxis.paser.ResultPaser.onParse(ResultPaser.java:41)
	at rxhttp.wrapper.param.ObservableParser$SyncParserObserver.onNext(ObservableParser.java:103)
	at rxhttp.wrapper.param.ObservableParser$SyncParserObserver.onNext(ObservableParser.java:54)
	at rxhttp.wrapper.param.ObservableCallEnqueue$HttpDisposable.onResponse(ObservableCallEnqueue.java:79)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

环境：
Android Studio Arctic Fox | 2020.3.1
使用 FastJsonConverter
rxhttp : "2.6.5",
rxhttp-compiler : "2.6.5",
rxlife : "2.1.0",
okhttp : "3.12.6",
rxandroid : "2.1.1",
rxjava : "2.2.8",
gson : "2.8.7",
converter-fastjson :2.6.5'

**Comment by liujingxing** [comment]
你要看请求开始日志，才知道有没有添加header；没有的话，就是你没添加，如果你有添加header的代码，调试下就知道了。

**Comment by chenyinchao** [comment]
> 你要看请求开始日志，才知道有没有添加header；没有的话，就是你没添加，如果你有添加header的代码，调试下就知道了。

这个问题是概现的，用着好好的突然出现

RxHttpPlugins.init(client).setConverter(FastJsonConverter.create()).setDebug(isDebug())
    .setOnParamAssembly(p -> {
        p.addHeader("Authorization", SPUtils.getInstance().getString("Authorization"));
        return p;
    });

**Comment by liujingxing** [comment]
你接口返回的够清楚了，`用户认证不通过，Token无效。` 自己调试下看看是否token过期了，或者故意传个错误的token试试就知道了

**Comment by chenyinchao** [comment]
> 你接口返回的够清楚了，`用户认证不通过，Token无效。` 自己调试下看看是否 token 过期了，或者故意传个错误的 token 试试就知道了

```
http/1.1 403
X-Application-Context: jl:project:8686
// 和正常请求的log对比，此处没有Authorization，是突然丢失的，所以才报403，不知道为什么，低概率出现
Content-Type: application/json;charset=utf-8
Transfer-Encoding: chunked
Date: Thu, 19 Aug 2021 02:13:13 GMT

{
"success": false,
"message": "用户认证不通过，Token 无效。"
}
```

**Comment by liujingxing** [comment]
你发的是响应头，自然没有Authorization，请求头才有

**Comment by liujingxing** [comment]
不要纠结Authorization丢失问题了，不可能会出现这个问题；你应该查的是，Token为啥会无效？传一个错误的token看看是否也返回同样的错误。

**Comment by chenyinchao** [comment]
> 不要纠结 Authorization 丢失问题了，不可能会出现这个问题；你应该查的是，Token 为啥会无效？传一个错误的 token 看看是否也返回同样的错误。

好的，感谢
