### ISSUE TITLE
fastjson解析报错

### ISSUE THREAD

**Issue by chenyinchao** [liujingxing/rxhttp#304]
fastjson解析报错了，而且日志是乱码
{
    "data": {
        "num1": 0E-8,
        "num2": 0E-8
    },
    "msg": "",
    "success": true
}

BigDecimal num1；
BigDecimal num2；

环境：
Android Studio Arctic Fox | 2020.3.1
使用 FastJsonConverter
rxhttp : "2.6.5",
rxhttp-compiler : "2.6.5",
rxlife : "2.1.0",
okhttp : "3.12.6",
rxandroid : "2.1.1",
rxjava : "2.2.8",
gson : "2.8.7",
converter-fastjson :2.6.5'

**Comment by liujingxing** [comment]
哪里乱码？报什么错？

**Comment by chenyinchao** [comment]
> 哪里乱码？报什么错？

java.lang.NumberFormatException: For input string: 
at java.lang.Integer.parseInt(Integer.java:521)
at java.lang.Integer.parseInt(Integer.java:556)
at java.math.BigDecimal.<init>(BigDecimal.java:336)
at java.math.BigDecimal.<init>(BigDecimal.java:374)
at com.alibaba.fastjson.parser.JSONLexerBase.scanFieldDecimal(JSONLexerBase.java:3727)
at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:594)
at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:295)
at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:291)
at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:88)
at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:1282)
at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:897)
at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:295)
at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:706)

Caused by: com.alibaba.fastjson.JSONException: For input string: 
at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:713)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:394)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:357)
at rxhttp.wrapper.converter.FastJsonConverter.convert(FastJsonConverter.java:59)
at rxhttp.wrapper.utils.Converter.convert(Converter.kt:45)
at rxhttp.wrapper.parse.AbstractParser.convert(AbstractParser.kt:33)
at com.galaxis.paser.ResultPaser.onParse(ResultPaser.java:41)
at rxhttp.wrapper.param.ObservableParser$SyncParserObserver.onNext(ObservableParser.java:103)
at rxhttp.wrapper.param.ObservableParser$SyncParserObserver.onNext(ObservableParser.java:54)
at rxhttp.wrapper.param.ObservableCallEnqueue$HttpDisposable.onResponse(ObservableCallEnqueue.java:79)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)

**Comment by chenyinchao** [comment]
> 这应该 fastjson 遇到数据类型不一样导致解析异常，你要自己去查

跟这个报错一样，
https://github.com/alibaba/fastjson/issues/3398
https://github.com/alibaba/fastjson/pull/3555

**Comment by liujingxing** [comment]
我试过了，是可以解析成功的
```java
public class Bean {

    private BigDecimal num1;
    private BigDecimal num2;

    //省略get、set方法
}
```
```
String json = "{\"num1\": 0E-8,\"num2\": 0E-8}";  
Bean bean = JSON.parseObject(json, Bean.class);
Log.e("LJX", "bean=" + bean);                   
```
```
2021-09-08 17:51:34.724 11165-11165/com.example.rxhttp E/LJX: bean=Bean{num1=0E-8, num2=0E-8}
```

检查下你用到fastjson版本，`converter-fastjson`内部用的1.2.76版本

**Comment by chenyinchao** [comment]
我用的就是com.github.liujingxing.rxhttp:converter-fastjson:2.6.8，没有指定fastjson，应该就是内部版本

**Comment by liujingxing** [comment]
自己试试上面那段代码
