### ISSUE TITLE
超时连带app一起崩溃了java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by ppg408331701** [liujingxing/rxhttp#330]
```
java.net.SocketTimeoutException: failed to connect to /172.192.10.148 (port 5010) from /192.168.2.123 (port 45360) after 15000ms
        at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
        at libcore.io.IoBridge.connect(IoBridge.java:135)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at rxhttp.wrapper.intercept.LogInterceptor.intercept(LogInterceptor.kt:27)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.gxrcw.activity.app.http.RefreshTokenInterceptor.intercept(RefreshTokenInterceptor.kt:28)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
```

我自己写了一个RefreshTokenInterceptor，用于刷新token，但是在连接ip地址超时的时候，会连带app一起崩溃
```
 override fun intercept(chain: Interceptor.Chain): Response {
        val request: Request = chain.request()
        val originalResponse = chain.proceed(request)//崩溃发生在这里

        val access_token = originalResponse.header("access-token")
        val x_access_token = originalResponse.header("x-access-token")
        if (!access_token.isNullOrEmpty()) CommonCacheUtil.setAccessToken(access_token)
        if (!x_access_token.isNullOrEmpty()) CommonCacheUtil.setXAccessToken(x_access_token)

        if (originalResponse.code == HTTP_CODE_ACCEPT) {
            try {
                val islogin = CommonCacheUtil.isLogin()
                if (islogin) {
                    CommonCacheUtil.setIsLogin(false)
                    val myCookieJar = RxHttpPlugins.getOkHttpClient().cookieJar as ICookieJar
                    myCookieJar.removeAllCookie()

                    val launchMode = MkTools.defaultSp().getString(CommonGlobal.launchMode, CommonGlobal.ModeGxrcw).toStringOrBlank()
                    if (launchMode == CommonGlobal.ModeGxrcw) {
                        ServiceUtil.exitGxrcw()
                    } else {
                        ServiceUtil.exitGxzpb()
                    }
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
        return originalResponse
    }
```

请问这种情况是该如何捕捉

**Comment by liujingxing** [comment]
发请求时，添加异常回调

**Comment by ppg408331701** [comment]
你这么一说，我确实有些接口没有写异常回调。
