### ISSUE TITLE
自定义Parser遇到data=null时，会直接抛异常

### ISSUE THREAD

**Issue by ppg408331701** [liujingxing/rxhttp#333]
自定义parser里面 Converter.convertTo()遇到data=null的情况时，
会抛出 java.io.EOFException   Request end Log printing failed 的异常
```
 public T onParse(@NotNull okhttp3.Response response) throws IOException {
        Response<T> data = Converter.convertTo(response, Response.class, types);//这一步直接抛出异常
        T t = data.getData(); //获取data字段
        if (t == null && types[0] == String.class) {
            t = (T) data.getMsg();
        }
        if (data.getCode() != 0 || t == null) {//code不等于0，说明数据不正确，抛出异常
            throw new ParseException(String.valueOf(data.getCode()), data.getMsg(), response);
        }
        return t;
    }
```
Response.class的定义如下
```
private int code;
private int httpCode;
private String message;
private T data;
```

返回的数据如下
{"code":0,"data":null,"message":"","now":"2021-12-02 08:36:29"}

请问这种情况如何自定义Parser规避好？

异常如下

```
java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
        at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.kt:381)
        at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.kt:429)
        at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:408)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
        at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
        at rxhttp.wrapper.utils.LogUtil.response2Str(LogUtil.java:308)
        at rxhttp.wrapper.utils.LogUtil.log(LogUtil.java:182)
        at rxhttp.wrapper.utils.Converter.convert(Converter.kt:43)
        at rxhttp.wrapper.parse.SimpleParser.onParse(SimpleParser.kt:20)
        at rxhttp.wrapper.utils.CallKt$await$4$2.onResponse(Call.kt:44)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
2021-12-02 16:33:35.171 18297-18297/com.gxrcw.activity W/System.err:     at rxhttp.wrapper.converter.GsonConverter.convert(GsonConverter.java:51)
2021-12-02 16:33:35.171 18297-18297/com.gxrcw.activity W/System.err:     at rxhttp.wrapper.utils.Converter.convert(Converter.kt:45)
2021-12-02 16:33:35.171 18297-18297/com.gxrcw.activity W/System.err:     at rxhttp.wrapper.parse.SimpleParser.onParse(SimpleParser.kt:20)
2021-12-02 16:33:35.171 18297-18297/com.gxrcw.activity W/System.err:     at rxhttp.wrapper.utils.CallKt$await$4$2.onResponse(Call.kt:44)
```

**Comment by liujingxing** [comment]
必现的吗？是的话，私聊我，327744707

**Comment by ppg408331701** [comment]
> 必现的吗？是的话，私聊我，327744707

目前能确定的是服务器那边由于某个条件判断失败了，导致的返回的数据在android上接受不到。
但是在ios和 浏览器的控制台可以解析出来。

后端是.net  在返回数据用的某个方法似乎会让source.request(Long.MAX_VALUE)抛出异常。

后端自己也不知道为什么，换了一个方法后解决了

**Comment by liujingxing** [comment]
用的rxhttp版本多少，日志打印失败按道理是不会影响请求的

**Comment by ppg408331701** [comment]
后端的描述是，当判断业余错误时。他会直接在http的响应头里中断。导致http连接提前中断了

okhttp就会抛出异常

**Comment by ppg408331701** [comment]
https://github.com/square/okio/issues/286
https://github.com/square/okhttp/issues/3113

有点类似这个，我昨天差到的，JakeWharton认为这个是正确的行为

**Comment by liujingxing** [comment]
看了下代码，确定有try catch语句，这个异常会导致app崩溃？

**Comment by ppg408331701** [comment]
> 看了下代码，确定有try catch语句，这个异常会导致app崩溃？

不会崩溃，只是捕捉到java.io.EOFException这个异常。但是ios又能解析出来，android解析不出来，所以昨天挠了一天的头

**Comment by liujingxing** [comment]
那这个只是日志打印异常，应该还有另外一个异常，有看过失败回调是什么异常吗？

**Comment by ppg408331701** [comment]
![image](https://user-images.githubusercontent.com/16531268/144531501-44c4d820-8057-4d18-be4f-192322c26dd0.png)
java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
        at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.kt:381)
        at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.kt:429)
        at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:408)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
        at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
        at rxhttp.wrapper.utils.LogUtil.response2Str(LogUtil.java:308)
        at rxhttp.wrapper.utils.LogUtil.log(LogUtil.java:182)
        at rxhttp.wrapper.utils.Converter.convert(Converter.kt:43)
        at rxhttp.wrapper.parse.SimpleParser.onParse(SimpleParser.kt:20)
        at rxhttp.wrapper.utils.CallKt$await$4$2.onResponse(Call.kt:44)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)

logcat就是显示这个异常

**Comment by ppg408331701** [comment]
我找到了这篇文章，应该就是这个描述的样子。
后端主动断开了和app的http连接导致的
https://www.codeleading.com/article/2064419567/

**Comment by liujingxing** [comment]
好的，我看看
