### ISSUE TITLE
post form addPart Uri NullPointerException: Parameter specified as non-null is null

### ISSUE THREAD

**Issue by echo326** [liujingxing/rxhttp#341]
如题，上传图片 通过addPart方式，报上面错误，rxHttp版本 2.4.1
Ur：file:///storage/emulated/0/Android/data/包名/cache/uhome/crop/1640254331862.jpg ，file:///data/user/0/包名/cache/uhome/crop/1640255408444.jpg ， file:///storage/emulated/0/Android/data/包名/files/Pictures/uhome/crop/1640255763869.jpg
调用方式： .addPart(getApplicationContext(), "file", uri)
调用代码如下：
```
 RxHttp.postForm(url)
     .addPart(getApplicationContext(), "file", uri)
     .asString()
     .subscribe((s) -> {
           LogFactory.e(s);
     }, (throwable) -> { });
```
日志错误：
  Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter $this$toMediaTypeOrNull
        at okhttp3.MediaType$Companion.parse(Unknown Source:2)
        at okhttp3.MediaType.parse(Unknown Source:2)
        at rxhttp.wrapper.entity.UriRequestBody.contentType(UriRequestBody.java:43)
        at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:134)
        at okhttp3.MultipartBody.contentLength(MultipartBody.kt:85)
        at rxhttp.wrapper.param.BodyParam.buildRequestBody(BodyParam.java:34)
        at rxhttp.wrapper.utils.BuildUtil.buildRequest(BuildUtil.java:27)
        at rxhttp.wrapper.param.AbstractParam.buildRequest(AbstractParam.java:210)
        at rxhttp.wrapper.param.RxHttp.buildRequest(RxHttp.java:469)
        at rxhttp.wrapper.param.RxHttp.newCall(RxHttp.java:461)
        at rxhttp.wrapper.param.ObservableCallEnqueue$HttpDisposable.<init>(ObservableCallEnqueue.java:66)
        at rxhttp.wrapper.param.ObservableCallEnqueue.subscribeActual(ObservableCallEnqueue.java:39)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at rxhttp.wrapper.param.ObservableParser.subscribeActual(ObservableParser.java:49)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.Observable.subscribe(Observable.java:12253)
        at io.reactivex.Observable.subscribe(Observable.java:12181)

**Comment by liujingxing** [comment]
贴上代码

**Comment by echo326** [comment]
> 贴上代码

已更新

**Comment by liujingxing** [comment]
升级新版本就好。另外，传绝对路径的对应的Uri是没有意义的

**Comment by echo326** [comment]
升级后解决
