### ISSUE TITLE
postJson数据中的key value带有空格会报错 MalformedJsonException

### ISSUE THREAD

**Issue by jalen2024** [liujingxing/rxhttp#370]
和这里描述一致。https://blog.csdn.net/u011374875/article/details/51956136

是否可以在GsonUtil中提供修改设置的地方呀。

```
public static Gson buildGson() {
        if (gson == null) {
            gson = new GsonBuilder()
                    .setLenient()//新增这个 或者暴露设置
                .disableHtmlEscaping()
                .registerTypeAdapter(String.class, new StringAdapter())
                .registerTypeAdapter(int.class, new IntegerDefault0Adapter())
                .registerTypeAdapter(Integer.class, new IntegerDefault0Adapter())
                .registerTypeAdapter(double.class, new DoubleDefault0Adapter())
                .registerTypeAdapter(Double.class, new DoubleDefault0Adapter())
                .registerTypeAdapter(long.class, new LongDefault0Adapter())
                .registerTypeAdapter(Long.class, new LongDefault0Adapter())
                .create();
        }
        return gson;
    }
```

**Comment by liujingxing** [comment]
可通过`GsonConverter.create(Gson)`传入自定义的Gson对象，随后，[设置Converter](https://github.com/liujingxing/rxhttp/wiki/%E8%AE%BE%E7%BD%AEConverter)即可

**Comment by jalen2024** [comment]
好的，谢谢。

**Comment by jalen2024** [comment]
想再请教下，我按照你说的去尝试做了
1: 将原有个rxhttp.wrapper.utils中的GsonUtil类复制出来一份修改成SafeGsonUtil, 只是新增了一行  `.setLenient()`
```
public static Gson buildGson() {
        if (gson == null) {
            gson = new GsonBuilder()
                    .disableHtmlEscaping()
                    .registerTypeAdapter(String.class, new StringAdapter())
                    .registerTypeAdapter(int.class, new IntegerDefault0Adapter())
                    .registerTypeAdapter(Integer.class, new IntegerDefault0Adapter())
                    .registerTypeAdapter(double.class, new DoubleDefault0Adapter())
                    .registerTypeAdapter(Double.class, new DoubleDefault0Adapter())
                    .registerTypeAdapter(long.class, new LongDefault0Adapter())
                    .registerTypeAdapter(Long.class, new LongDefault0Adapter())
                    .setLenient()
                    .create();
        }
        return gson;
    }
```
2: 新增如下的类，

```
public class RxHttpManager {
    @Converter(name = "SafeGsonConverter") //指定Converter名称
    public static IConverter safeGsonConverter = GsonConverter.create(SafeGsonUtil.buildGson());
}
```

3： 在Application启动类中修改如下
```
 RxHttpPlugins.init(NetHttpClient.getDefaultOkHttpClient().build())
            .setConverter(RxHttpManager.safeGsonConverter)
```

4: 在新增地址的接口中特地修改成  ` setSafeGsonConverter()`的方式去处理，但还是会出现上面的报错。

```
  fun addAddress(bean: AddressRequestBean): Await<Any> {
        return RxHttp.postJson(NetUrl.ADD_USER_ADDRESS).apply {
            setSafeGsonConverter()
            bean.cityId?.let { addJsonElementBySafe("cityId", it) }
            bean.cityName?.let { addJsonElementBySafe("cityName", it) }
            bean.countyId?.let { addJsonElementBySafe("countyId", it) }
            bean.countyName?.let { addJsonElementBySafe("countyName", it) }
            bean.defaultFlag?.let { addJsonElementBySafe("defaultFlag", it.toString()) }
            bean.detailAddress?.let { addJsonElementBySafe("detailAddress", it) }
            bean.phone?.let { addJsonElementBySafe("phone", it) }
            bean.provinceId?.let { addJsonElementBySafe("provinceId", it) }
            bean.provinceName?.let { addJsonElementBySafe("provinceName", it) }
            bean.username?.let { addJsonElementBySafe("username", it) }
            bean.zipCode?.let { addJsonElementBySafe("zipCode", it) }
        }.toResponse()
    }
```

5: 报错如下 `JsonSyntaxException`
```
at rxhttp.wrapper.param.JsonParam.addJsonElement(JsonParam.java:73)
at rxhttp.wrapper.param.RxHttpJsonParam.addJsonElement(RxHttpJsonParam.java:58)
at me.hgj.mvvmhelper.ext.NetCallbackExtKt$rxHttpRequest$1.invokeSuspend(NetCallbackExt.kt:34)
at me.hgj.mvvmhelper.ext.NetCallbackExtKt.rxHttpRequest(NetCallbackExt.kt:22)
```

**Comment by liujingxing** [comment]
`addJsonElement(String,String)`方法第二个参数要求是一个json字符串

**Comment by jalen2024** [comment]
感谢，可以正常使用了。
