### ISSUE TITLE
下载apk问题，下载过程时不时会出现下面的问题，不知道是服务端下载链接问题 还是本地少做了什么操作吗

### ISSUE THREAD

**Issue by WhiteCjy** [liujingxing/rxhttp#371]
022-05-15 13:05:32.224 26861-26898/com.bcg.walletgames.debug W/System.err: java.net.ProtocolException: unexpected end of stream
2022-05-15 13:05:32.225 26861-26898/com.bcg.walletgames.debug W/System.err:     at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:371)
2022-05-15 13:05:32.225 26861-26898/com.bcg.walletgames.debug W/System.err:     at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
2022-05-15 13:05:32.225 26861-26898/com.bcg.walletgames.debug W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
2022-05-15 13:05:32.225 26861-26898/com.bcg.walletgames.debug W/System.err:     at rxhttp.wrapper.cahce.CacheManager$2.read(CacheManager.java:175)
2022-05-15 13:05:32.225 26861-26898/com.bcg.walletgames.debug W/System.err:     at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
2022-05-15 13:05:32.225 26861-26898/com.bcg.walletgames.debug W/System.err:     at rxhttp.wrapper.utils.IOUtil.suspendWrite(IOUtil.kt:153)
2022-05-15 13:05:32.225 26861-26898/com.bcg.walletgames.debug W/System.err:     at rxhttp.wrapper.parse.SuspendStreamParserKt.writeTo(SuspendStreamParser.kt:56)
2022-05-15 13:05:32.225 26861-26898/com.bcg.walletgames.debug W/System.err:     at rxhttp.wrapper.parse.SuspendStreamParserKt.access$writeTo(SuspendStreamParser.kt:1)
2022-05-15 13:05:32.225 26861-26898/com.bcg.walletgames.debug W/System.err:     at rxhttp.wrapper.parse.SuspendStreamParser.onSuspendParse(SuspendStreamParser.kt:33)
2022-05-15 13:05:32.225 26861-26898/com.bcg.walletgames.debug W/System.err:     at rxhttp.wrapper.coroutines.AwaitImpl.await(AwaitImpl.kt:25)
2022-05-15 13:05:32.225 26861-26898/com.bcg.walletgames.debug W/System.err:     at rxhttp.wrapper.coroutines.AwaitImpl$await$1.invokeSuspend(Unknown Source:14)
2022-05-15 13:05:32.225 26861-26898/com.bcg.walletgames.debug W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-05-15 13:05:32.226 26861-26898/com.bcg.walletgames.debug W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-05-15 13:05:32.226 26861-26898/com.bcg.walletgames.debug W/System.err:     at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
2022-05-15 13:05:32.226 26861-26898/com.bcg.walletgames.debug W/System.err:     at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2022-05-15 13:05:32.226 26861-26898/com.bcg.walletgames.debug W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2022-05-15 13:05:32.226 26861-26898/com.bcg.walletgames.debug W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-05-15 13:05:32.226 26861-26898/com.bcg.walletgames.debug W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2022-05-15 13:05:32.226 26861-26898/com.bcg.walletgames.debug W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-05-15 13:05:32.226 26861-26898/com.bcg.walletgames.debug E/RxHttp: java.net.ProtocolException: unexpected end of stream

**Comment by WhiteCjy** [comment]
RxHttp.get(downloadUrl)
                  .connectTimeout(300*1000)
                  .readTimeout(300*1000)
                  .writeTimeout(300*1000)
                  .toFlow(apkFile!!.path, true) {
                      val currentProgress = it.progress //当前进度 0-100
                      val currentSize = it.currentSize  //当前已上传的字节大小
                      val totalSize = it.totalSize      //要上传的总字节大小
               }

**Comment by liujingxing** [comment]
Content-Length跟文件实际长度不一致

**Comment by WhiteCjy** [comment]
这个不是http自己计算的吗，文件直接从文件服务器下过来

**Comment by liujingxing** [comment]
看日志里的Content-Length响应头，对比下文件实际长度就知道了

**Comment by WhiteCjy** [comment]
问题是浏览器能正常下载，服务端觉得没问题，文件实际长度也应该没问题吧 看了下

**Comment by liujingxing** [comment]
```kotlin
    override fun read(sink: Buffer, byteCount: Long): Long {
      require(byteCount >= 0L) { "byteCount < 0: $byteCount" }
      check(!closed) { "closed" }
      if (bytesRemaining == 0L) return -1

      val read = super.read(sink, minOf(bytesRemaining, byteCount))
      if (read == -1L) {
        connection.noNewExchanges() // The server didn't supply the promised content length.
        val e = ProtocolException("unexpected end of stream")
        responseBodyComplete()
        throw e
      }

      bytesRemaining -= read
      if (bytesRemaining == 0L) {
        responseBodyComplete()
      }
      return read
    }
```
这是okhttp的中的`Http1ExchangeCodec`类源码，看上面的注释就懂了

**Comment by WhiteCjy** [comment]
重点是不知道为什么不一致啊

**Comment by android-1995** [comment]
@WhiteCjy 解决了吗？同样的一个问题

**Comment by liujingxing** [comment]
> <img alt="@WhiteCjy" width="20" height="20" src="https://avatars.githubusercontent.com/u/22490946?s=60&amp;u=4734caed4d4f71feba159da83781b88e08cbb75f&amp;v=4">

如果是必现的，麻烦提供下载链接，不方便就加我微信私发我 `ljx-studio`

**Comment by liujingxing** [comment]
> @WhiteCjy 解决了吗？差不多的一个问题，我这边第一次会报 java.net.ProtocolException: unexpected end of stream，再次下载同一个文件就正常了

如果是必现的，麻烦提供下载链接，不方便就加我微信私发我 `ljx-studio`

**Comment by android-1995** [comment]
> > <img alt="@WhiteCjy" width="20" height="20" src="https://avatars.githubusercontent.com/u/22490946?s=60&amp;u=4734caed4d4f71feba159da83781b88e08cbb75f&amp;v=4">
> 
> 如果是必现的，麻烦提供下载链接，不方便就加我微信私发我 `ljx-studio`

我这不是库的原因，是服务端和客户端的对接问题
