### ISSUE TITLE
2.9.2版本，`asResponse<Int>()`方法，泛型为基本类型时，使用`Gson`解析，报`IllegalArgumentException`异常，其它版本没问题

### ISSUE THREAD

**Issue by liujingxing** [liujingxing/rxhttp#399]
```java
java.lang.IllegalArgumentException
    at com.google.gson.internal.$Gson$Preconditions.checkArgument($Gson$Preconditions.java:46)
    at com.google.gson.internal.$Gson$Types.checkNotPrimitive($Gson$Types.java:480)
    at com.google.gson.internal.$Gson$Types$ParameterizedTypeImpl.<init>($Gson$Types.java:502)
    at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:116)
    at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:75)
    at com.google.gson.reflect.TypeToken.get(TypeToken.java:309)
    at com.google.gson.Gson.fromJson(Gson.java:1056)
    at com.google.gson.Gson.fromJson(Gson.java:1016)
    at com.google.gson.Gson.fromJson(Gson.java:959)
    at rxhttp.wrapper.converter.GsonConverter.convert(GsonConverter.java:62)
    at rxhttp.wrapper.utils.Converter.convert(Converter.kt:45)
    at rxhttp.wrapper.utils.Converter.convertTo(Converter.kt:26)
    at rxhttp.wrapper.utils.Converter.convertTo(Converter.kt:21)
    at com.example.httpsender.parser.ResponseParser.onParse(ResponseParser.kt:44)
    at rxhttp.wrapper.param.ObservableParser$SyncParserObserver.onNext(ObservableParser.java:102)
    at rxhttp.wrapper.param.ObservableParser$SyncParserObserver.onNext(ObservableParser.java:52)
    at rxhttp.wrapper.param.ObservableCallEnqueue$HttpDisposable.onResponse(ObservableCallEnqueue.java:79)
    at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)
```

**Comment by liujingxing** [comment]
经详细测试后发现，Java环境下`asClass(Class<T>)`、`asResponse(Class<T>)`，传入基本类型，如：`asClass(int.class)`，只要用`Gson`解析，任意版本皆可复现此问题

**Comment by liujingxing** [comment]
`Gson`遇到`ParameterizedType`类型，会校验其`actualTypeArguments`数据，如果是基本数据类型，则抛出`java.lang.IllegalArgumentException`异常

**Comment by liujingxing** [comment]
[2.9.3版本已解决该问题](https://github.com/liujingxing/rxhttp/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)
