### ISSUE TITLE
服务端一直获取不到cookie里的sessionID，急！！！！！

### ISSUE THREAD

**Issue by 429329513wanting** [liujingxing/rxhttp#419]
版本：    api 'com.ljx.rxhttp:rxhttp:2.2.8'，
接口端获取iOS端请求能正常获取，iOS也没手动额外处理cookie
初始化代码如下：        
```kotlin
        val cacheCookie = File(Utils.getApp().externalCacheDir, "RxHttpCookie")
        cookieStore = CookieStore(cacheCookie)
        val client2 = OkHttpClient.Builder().cookieJar(cookieStore)
        // debug模式就添加日志拦截器
        if (BuildConfig.DEBUG) {
            client2.addInterceptor(mLogInterceptor)
        }

        // 初始化
        RxHttp.init(getDefaultOkHttpClient().build(), BuildConfig.DEBUG)
```

**Comment by 429329513wanting** [comment]
RxHttp.init(client2.build(), BuildConfig.DEBUG)

**Comment by liujingxing** [comment]
请提供RxHttp的完整日志

**Comment by 429329513wanting** [comment]
url：https://pms.sendinfo.com.cn/manage/admin/webApi/priHotelMerchantUser/hotelMerchantList
    │ method：POST 
    │ 耗时：129毫秒
    │ date：2023-02-09 14:08:57 
    │ product：系统=android9 ,厂商=Genymotion ,手机型号=P30 Pro 
    │ code：401 
    │ protocol：h2
    │ message：
    │ header：device-type=phone
    │ header：sign=8070631c3804b43fc71852fef6f71fecad7577e7cb2098804090f0c00e31a7bf
    │ header：sk=V45laJF65TWK%2Fft5LhdHulcIP%2BU28kxF8t6vzhS7qYYRSX2LaaSK7bL5L4s0T01mJbhuCOHsOJAX0r2aNA1YbQ6TC2txtVpJoHyibur4eN2kO%2Fv1w%2F4T6sJbML%2F0wAQVg2FbbRPSOWJRaK03SWZO%2BEn7wY7brnDrPy1zKSQgStT1wRxrMnkhbfIOYK7%2FUb09R4LKMhmFuNY%2BX2Q7T%2BJaQFqlD0lXMvUPEvtrpEB%2BuIdMM8i5uJdgp0B8F%2F8KokIcsGLjRbkpKEf8g6nUOzC1aRAQT9casNN4npNcpcH2dG7%2FVS7F7RgJ%2Fdaen5wYbQlKGaYEWgIUehmxVKdNyAhizw%3D%3D
    │ params：{corpCode=ZZZZZZ}
    │ ContentType : t
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2023-02-09 14:08:57.867 9872-10034/com.sendinfo.coludpms D/SEND_PMS:  
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ ext/html;charset=UTF-8 
    │ 响应结果:
    │ 
    │ {"timestamp":1675922940481,"status":401,"error":"Bad Request","exception":"token验证","message":"请先登录"}
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2023-02-09 14:08:58.019 9872-9872/com.sendinfo.coludpms D/VMViewModel: 请求失败
2023-02-09 14:08:58.030 9872-9872/com.sendinfo.coludpms D/SEND_PMS:  
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ main, com.base.library.base.BActivity.modifyPasswordFinish(BActivity.kt:67)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ token_verification 请先登录
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2023-02-09 14:08:58.044 9872-9872/com.sendinfo.coludpms D/SEND_PMS:  
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ main, com.base.library.base.BActivity.modifyPasswordFinish(BActivity.kt:67)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ token_verification 请先登录
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2023-02-09 14:08:58.054 9872-9872/com.sendinfo.coludpms V/OnCallback: onError - msg=请先登录 - url=/manage/admin/webApi/priHotelMerchantUser/hotelMerchantList - isFinish=false - isSilence=false
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: rxhttp.wrapper.exception.HttpStatusCodeException: Method=POST Code=401
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: message = 
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: 
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: https://pms.sendinfo.com.cn/manage/admin/webApi/priHotelMerchantUser/hotelMerchantList
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: 
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: corpCode=ZZZZZZ
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: 
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: server: Tengine
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: date: Thu, 09 Feb 2023 06:09:45 GMT
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: content-type: text/html;charset=UTF-8
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: set-cookie: tr_se_id=c2UtUEdDV0xSUUtLTldP%0A; Path=/; Domain=.sendinfo.com.cn; Max-Age=7200; Expires=Thu, 09 Feb 2023 08:09:00 GMT; Secure; SameSite=None
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: set-cookie: tr_de_id=ZHYtVllRR1JKWVlLR0pU%0A; Path=/; Domain=.sendinfo.com.cn; Max-Age=2147483647; Expires=Tue, 27 Feb 2091 09:23:07 GMT; Secure; SameSite=None
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: set-cookie: tr_wb_id=d2ItRUxGUk9SQVdTSU5U%0A; Path=/; Domain=.sendinfo.com.cn; Secure; SameSite=None
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: vary: Origin
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: vary: Access-Control-Request-Method
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: vary: Access-Control-Request-Headers
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: set-cookie: SESSIONID=275db46f-78a0-4748-9f0c-60c54c9c475e; Path=/
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: set-cookie: SESSIONID=1409004797140c0b6-aae1-48ab-9285-b06b29d7851a; Path=/
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: 
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err: {"timestamp":1675922940481,"status":401,"error":"Bad Request","exception":"token验证","message":"请先登录"}
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err:     at rxhttp.wrapper.exception.ExceptionHelper.throwIfFatal(ExceptionHelper.java:33)
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err:     at rxhttp.wrapper.parse.Parser$DefaultImpls.convert(Parser.kt:49)
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err:     at rxhttp.wrapper.parse.AbstractParser.convert(AbstractParser.kt:13)
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err:     at com.base.library.rxhttp.RxHttpParser.onParse(RxHttpParser.kt:34)
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err:     at com.base.library.rxhttp.RxHttpParser.onParse(RxHttpParser.kt:12)
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err:     at rxhttp.wrapper.param.ObservableHttp.execute(ObservableHttp.java:109)
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err:     at rxhttp.wrapper.param.ObservableHttp.subscribeActual(ObservableHttp.java:58)
2023-02-09 14:08:58.071 9872-9872/com.sendinfo.coludpms W/System.err:     at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
2023-02-09 14:08:58.072 9872-9872/com.sendinfo.coludpms W/System.err:     at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2023-02-09 14:08:58.072 9872-9872/com.sendinfo.coludpms W/System.err:     at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:589)
2023-02-09 14:08:58.072 9872-9872/com.sendinfo.coludpms W/System.err:     at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
2023-02-09 14:08:58.072 9872-9872/com.sendinfo.coludpms W/System.err:     at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
2023-02-09 14:08:58.072 9872-9872/com.sendinfo.coludpms W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2023-02-09 14:08:58.072 9872-9872/com.sendinfo.coludpms W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2023-02-09 14:08:58.072 9872-9872/com.sendinfo.coludpms W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2023-02-09 14:08:58.072 9872-9872/com.sendinfo.coludpms W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2023-02-09 14:08:58.072 9872-9872/com.sendinfo.coludpms W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by 429329513wanting** [comment]
这个报错，接口说是cookie里没有取到sessionid,

**Comment by liujingxing** [comment]
找到有返回cookie的接口，日志截图出来

**Comment by liujingxing** [comment]
`ICookieJar#saveFromResponse(HttpUrl,List)`自己去调试看看

**Comment by 429329513wanting** [comment]
> `ICookieJar#saveFromResponse(HttpUrl,List)`自己去调试看看

接口那边问题，每次接口返回的cookie里的sessionID都会变的。。。，坑啊
