### ISSUE TITLE
fastjson解析器， data class 解析失败：com.alibaba.fastjson.JSONException: default constructor not found.

### ISSUE THREAD

**Issue by baowenqing** [liujingxing/rxhttp#441]
异常报错如下：
```
 https://www.wanandroid.com/article/list/0/json?method=get&versionName=1.0.0&time=1687069772082
 com.alibaba.fastjson.JSONException: default constructor not found. class com.example.httpsender.entity.Ar
 	at com.alibaba.fastjson.util.JavaBeanInfo.build(JavaBeanInfo.java:574)
 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.<init>(JavaBeanDeserializer.java:46)
 	at com.alibaba.fastjson.parser.ParserConfig.createJavaBeanDeserializer(ParserConfig.java:1077)
 	at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:888)
 	at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:593)
 	at com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer.parseArray(ArrayListTypeFi
 	at com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer.parseField(ArrayListTypeFi
 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java
 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java
 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java
 	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeseriali
 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java
 	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java
 	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:706)
 	at com.alibaba.fastjson.JSON.parseObject(JSON.java:394)
 	at com.alibaba.fastjson.JSON.parseObject(JSON.java:357)
 	at rxhttp.wrapper.converter.FastJsonConverter.convert(FastJsonConverter.java:65)
 	at rxhttp.wrapper.utils.Converter.convert(Converter.java:46)
 	at rxhttp.wrapper.utils.Converter.convertTo(Converter.java:24)
 	at rxhttp.wrapper.utils.ConverterKt.convertTo(Converter.kt:19)
 	at rxhttp.wrapper.utils.ConverterKt.convertTo(Converter.kt:15)
 	at com.example.httpsender.parser.ResponseParser.onParse(ResponseParser.kt:44)
 	at rxhttp.wrapper.param.ObservableCall$CallEnqueueDisposable.onResponse(ObservableCall.java:116)
 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

14:29:33.832 RxHttp               com...mple.rxhttp  E  	at java.lang.Thread.run(Thread.java:764)
```
 

代码修改如下：

增加了一个 data  class
```
package com.example.httpsender.entity

data class ArticleNew(
      var audit: Int = 0,
              val author: String? = null
)

```
2.修改了rxJava下的get请求中的类
![image](https://github.com/liujingxing/rxhttp/assets/20606825/323c0872-cf3d-4b5d-a6aa-097f703e70fc)

**Comment by baowenqing** [comment]
我试了下 用fastjson解析器  解析 java实体类是没有问题的  但是kotlin下的data class  就会报错 com.alibaba.fastjson.JSONException: default constructor not found. 【Gson的解析器没问题】

麻烦作者帮忙看看  fastjson解析器  能不能帮忙修复下     兼容这种data class

**Comment by liujingxing** [comment]
这是fastjson的问题，我解决不了
