### ISSUE TITLE
空指针异常   at rxhttp.ObservableParser.subscribeActual(ObservableParserjava2）

### ISSUE THREAD

**Issue by yuanmaio** [liujingxing/rxhttp#451]
```
 java.lang.NullPointerException: Actually not, but can't throw other exceptions due to RS
07-07 15:46:19.092 W/System.err( 7348): 	at io.reactivex.Observable.subscribe(Observable.java:7)
07-07 15:46:19.092 W/System.err( 7348): 	at rxhttp.ObservableParser.a(ObservableParser.java:2)
07-07 15:46:19.092 W/System.err( 7348): 	at io.reactivex.Observable.subscribe(Observable.java:4)
07-07 15:46:19.093 W/System.err( 7348): 	at io.reactivex.internal.operators.observable.ObservableObserveOn.a(ObservableObserveOn.java:4)
07-07 15:46:19.093 W/System.err( 7348): 	at io.reactivex.Observable.subscribe(Observable.java:4)
07-07 15:46:19.093 W/System.err( 7348): 	at io.reactivex.internal.operators.observable.ObservableDetach.a(ObservableDetach.java:1)
07-07 15:46:19.093 W/System.err( 7348): 	at io.reactivex.Observable.subscribe(Observable.java:4)
07-07 15:46:19.093 W/System.err( 7348): 	at com.rxjava.rxlife.ObservableLife.b(ObservableLife.java:4)
07-07 15:46:19.093 W/System.err( 7348): 	at com.rxjava.rxlife.ObservableLife.a(ObservableLife.java:12)
07-07 15:46:19.093 W/System.err( 7348): 	at com.rxjava.rxlife.ObservableLife.a(ObservableLife.java:8)
07-07 15:46:19.093 W/System.err( 7348): 	at com.rxjava.rxlife.ObservableLife.a(ObservableLife.java:1)
07-07 15:46:19.093 W/System.err( 7348): 	at com.smartcity.business.utils.UpdateUtil.a(UpdateUtil.java:6)
07-07 15:46:19.093 W/System.err( 7348): 	at com.smartcity.business.activity.LoginActivity.onCreate(LoginActivity.java:2)
07-07 15:46:19.093 W/System.err( 7348): 	at android.app.Activity.performCreate(Activity.java:7458)
07-07 15:46:19.093 W/System.err( 7348): 	at android.app.Activity.performCreate(Activity.java:7448)
07-07 15:46:19.093 W/System.err( 7348): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
07-07 15:46:19.093 W/System.err( 7348): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
07-07 15:46:19.093 W/System.err( 7348): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
07-07 15:46:19.093 W/System.err( 7348): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
07-07 15:46:19.093 W/System.err( 7348): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
07-07 15:46:19.093 W/System.err( 7348): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
07-07 15:46:19.093 W/System.err( 7348): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
07-07 15:46:19.093 W/System.err( 7348): 	at android.os.Handler.dispatchMessage(Handler.java:112)
07-07 15:46:19.093 W/System.err( 7348): 	at android.os.Looper.loop(Looper.java:216)
07-07 15:46:19.093 W/System.err( 7348): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
07-07 15:46:19.093 W/System.err( 7348): 	at java.lang.reflect.Method.invoke(Native Method)
07-07 15:46:19.093 W/System.err( 7348): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
07-07 15:46:19.093 W/System.err( 7348): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

用的这个版本
  implementation 'com.github.liujingxing.rxhttp:rxhttp:2.6.1'
    annotationProcessor 'com.github.liujingxing.rxhttp:rxhttp-compiler:2.6.1'

**Comment by liujingxing** [comment]
更新版本就好
