### ISSUE TITLE
R8 full mode 完整模式兼容问题

### ISSUE THREAD

**Issue by liujingxing** [liujingxing/rxhttp#471]
RxHttp 版本 v3.2.0

通过`android.enableR8.fullMode=true`开启R8完整模式，或将`AGP`升级至8.0及以上版本，将默认开启完整模式，此时执行以下代码，将发生闪退
```kotlin
RxHttp.get("...")
   .toXxx(object: SmartParser<Xxx>(){})   //通过匿名内部类，创建任意继承TypeParser的类
   ...

```

闪退日志

```xml
java.lang.RuntimeException: Missing type parameter.
   at rxhttp.wrapper.utils.TypeUtil.getActualTypeParameters(TypeUtil.java:23)
   at rxhttp.wrapper.parse.TypeParser.<init>(TypeParser.java:18)
   at com.example.httpsender.parser.ResponseParser.<init>(ResponseParser.kt:32)
```

**Comment by liujingxing** [comment]
出现该问题的原因是，完整模式下，对于没有keep的类，将会擦出泛型信息

目前有3个解决方案

1、手动关闭完整模式，在`gradle.properties`文件中添加以下代码

```
android.enableR8.fullMode=false
```

2、添加以下规则到`proguard-rules.pro`文件中

```
-keep,allowobfuscation,allowshrinking class * extends rxhttp.wrapper.parse.TypeParser
```

3、升级RxHttp至`v3.2.1`或更高版本

**Comment by liujingxing** [comment]
如果项目中有自定义解析器，并且使用了类似于`BaseResponse<T>`的类，也要添加以下规则到``文件中

```gradle
-keep,allowobfuscation,allowshrinking class xxx.xxx.BaseResponse
```

其中`xxx.xxx`是类路径
