### ISSUE TITLE
有时候后台会返回一些意想不到的json

### ISSUE THREAD

**Issue by GXSZone** [liujingxing/rxhttp#485]
转换错误直接就嘎了，建议写个兜底策略
```
Tunnel suiy25.natappfree.cc not found
12:17:25.180 RxHttp                   E  rxhttp.wrapper.exception.HttpStatusCodeException: http/1.0 404 Not Found, http://suiy25.natappfree.cc/user/v1/phone/send
12:17:25.180 RxHttp                   E  	at rxhttp.wrapper.OkHttpCompat.throwIfFail(OkHttpCompat.java:122)
12:17:25.180 RxHttp                   E  	at rxhttp.wrapper.utils.Converter.convert(Converter.java:33)
12:17:25.180 RxHttp                   E  	at rxhttp.wrapper.parse.SmartParser.onParse(SmartParser.java:27)
12:17:25.180 RxHttp                   E  	at rxhttp.wrapper.utils.Utils$await$2$2.onResponse(Utils.kt:37)
12:17:25.180 RxHttp                   E  	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
12:17:25.180 RxHttp                   E  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
12:17:25.180 RxHttp                   E  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
12:17:25.180 RxHttp                   E  	at java.lang.Thread.run(Thread.java:1012)
12:17:25.196 DEBUG                    E  encryptLog: false, zipCrashLog: false
12:17:25.196 DEBUG                    E  begin to generate java report
12:17:25.201 DEBUG                    E  *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12:17:25.201 DEBUG                    E  Basic Information: 'pid: 6266/tid: 6266/time: 20240211121725'
```

**Comment by liujingxing** [comment]
这么早就开工了吗？只要出现异常，都会走异常回调，下一个，你这也不是啥转换错误，你接口404了

**Comment by liujingxing** [comment]
你需要自己设置一个异常回调

**Comment by liujingxing** [comment]
不会的，提供下代码

**Comment by liujingxing** [comment]
有一系列await方法，可以捕获异常，不需要自己写try语句。如tryAwait、awaitResult方法
